### ISSUE TITLE
A bug in the brain_dataset.py

### ISSUE THREAD

**Issue by Gemaxis** [HennyJie/BrainGB#15]
Hi,

This is excellent work, but I found a bug in **brain_dataset.py**.
At the function named **dense_to_ind_val**, **torch.isnan(adj)==0** will make every existing value turn into True, causing the **index** fully True which means every brain network is fully connected.

**Comment by yangji9181** [comment]
Thanks For the comments. The brain networks are indeed fully connected, which are different from most graphs in other domains.
