### ISSUE TITLE
datasets downloader

### ISSUE THREAD

**Issue by 19980715dyy** [HennyJie/BrainGB#2]
ABCD/abcd_rest-timeseires-HCP2016.npy
514_timeseries.npy
/abide.npy
How do I get these downloaded files? Sorry, I'm a novice. I visited the official data website, but I have no clue

**Comment by HennyJie** [comment]
Hi,
You can refer to the example [here](https://github.com/Wayfear/FBNETGEN/tree/main/util/abide) for downloading and preprocessing the ABIDE dataset.

**Comment by 19980715dyy** [comment]
> thank you
