### ISSUE TITLE
Hello. when i run this code on cuda environment this error happend. would you please help me fixing it?

### ISSUE THREAD

**Issue by wenjie-666** [HennyJie/BrainGB#21]
ValueError: Encountered tensor with size 640000 in dimension 0, but expected size 3200.
It seems that it's because of this code： z = conv(z, edge_index, edge_attr) in gat.py
It doesn't seem as simple as the official website suggests：For a GAT-based setup, simply replace the GCN model initializations with GAT.

**Comment by salmon1802** [comment]
I meet the same problem as you. How did you solve it？

**Comment by ZKY315** [comment]
> I meet the same problem as you. How did you solve it？

Did you solve the problem?

**Comment by ZKY315** [comment]
> ValueError: Encountered tensor with size 640000 in dimension 0, but expected size 3200. It seems that it's because of this code： z = conv(z, edge_index, edge_attr) in gat.py It doesn't seem as simple as the official website suggests：For a GAT-based setup, simply replace the GCN model initializations with GAT.

I met the same problem, did you solve it?

**Comment by salmon1802** [comment]
> > ValueError: Encountered tensor with size 640000 in dimension 0, but expected size 3200. It seems that it's because of this code： z = conv(z, edge_index, edge_attr) in gat.py It doesn't seem as simple as the official website suggests：For a GAT-based setup, simply replace the GCN model initializations with GAT.
> 
> I met the same problem, did you solve it?

I solved this problem by modifying the pytorch version as described in #29

**Comment by ZKY315** [comment]
> > > ValueError: Encountered tensor with size 640000 in dimension 0, but expected size 3200. It seems that it's because of this code： z = conv(z, edge_index, edge_attr) in gat.py It doesn't seem as simple as the official website suggests：For a GAT-based setup, simply replace the GCN model initializations with GAT.
> > 
> > 
> > I met the same problem, did you solve it?
> 
> I solved this problem by modifying the pytorch version as described in #29

Thanks! I also solved it by modify the GAT and MessagePassing class with the prior PyG version (2.0.4).
