### ISSUE TITLE
Step 4: Label Generation reg_FSROI_Jan2014.sh

### ISSUE THREAD

**Issue by PolinaDruzhinina** [HennyJie/BrainGB#6]
I try to run you preprocessing steps for PPMI dataset. And faced with errors on the  Label Generation step 4. 

Could you tell me at what step and how do you get brainmask.mgz, rawavg.mgz, aparc+aseg.mgz files for your script reg_FSROI_Jan2014.sh ? Did you use dt-recon ?

**Comment by tonychengu** [comment]
These files should be included with Freesurfer and you should get it from about lines 13~17 in the reg_FSROI_Jan2014.sh

**Comment by PolinaDruzhinina** [comment]
Thank for your reply! 
But could you clarify as far as I can see these lines (13~17) are already using  files  brainmask.mgz /aparc+aseg.mgz as input, for example
$FREESURFER_HOME/bin/mri_vol2vol --mov brainmask.mgz

So, initially brainmask.mgz can be obtained as output from the recon-all command on structural images?

**Comment by tonychengu** [comment]
Sorry for the confusion. You are right. As far as I know, these .mgz files seem to be auto generated from the process you convet raw MRI to .nii file. The brianmask file would highlight the brain tissue area and the aseg would help do the segmentation for brain regions. I think recon-all will do the job.
